//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTestScoreView
    {
        public long CandidateTestDetailId { get; set; }
        public long CandidateTestId { get; set; }
        public long QuestionId { get; set; }
        public string Answer { get; set; }
        public long UserId { get; set; }
        public Nullable<int> TotalScore { get; set; }
        public Nullable<decimal> ObtainScore { get; set; }
        public string AnswerResult { get; set; }
    }
}
