//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class TestConfigurationDetail
    {
        public long TestConfigDetailId { get; set; }
        public int TestConfigId { get; set; }
        public string DifficultyLevel { get; set; }
        public int DecissionCount { get; set; }
        public int DecissionPercentage { get; set; }
    
        public virtual TestConfiguration TestConfiguration { get; set; }
    }
}
