//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Repository
{
    using System;
    using System.Collections.Generic;
    
    public partial class CandidateTestDetail
    {
        public long CandidateTestDetailId { get; set; }
        public long CandidateTestId { get; set; }
        public long QuestionId { get; set; }
        public string Answer { get; set; }
        public Nullable<System.DateTime> StartTime { get; set; }
        public Nullable<System.DateTime> EndTime { get; set; }
    
        public virtual CandidateTest CandidateTest { get; set; }
        public virtual Question Question { get; set; }
    }
}
